/* This file is automatically generated with "make proto". DO NOT EDIT */

int vstream_check_crc(void *buf, int length, u32 *crc);
void vstream_mfs_readahead(int set);
void vserver_vstream_read_sectors(void *buf, u32 sec, u32 count);
void vstream_io_need_bswap(int set);
void vstream_mfs_read_partial(void *buf, u32 sec, u32 size);
void vstream_set_socket_fd(int fd);
int vstream_open_socket(char *addy);
unsigned vstream_fsid_hash(unsigned fsid, unsigned size);
int load_super(void);
int load_zones(void);
u32 vstream_mfs_fsid_pread(int fsid, void *buf, u64 ofs, u32 count);
int vstream_mfs_fsid_type(int fsid);
u64 vstream_mfs_fsid_size(int fsid);
struct mfs_dirent *mfs_dir(int fsid, u32 *count);
void vstream_mfs_dir_free(struct mfs_dirent *dir);
u32 vstream_mfs_resolve(char *path);
void vstream_parse_object(int fsid, void *buf, object_fn fn);
int vstream_partition_parse(void);
u32 vstream_partition_total_size(void);
void *vstream_query_part(int fsid, int subobj, char *name, int *len);
void *vstream_query_path(int fsid, char *path, int *len);
char *vstream_query_string(int fsid, char *path);
int vstream_query_int(int fsid, char *path);
struct mfs_obj_attr *query_object(int fsid, char *path, int *count);
void load_callback2(int fsid, struct mfs_subobj_header *obj,
		    struct mfs_attr_header *attr, void *data);
void load_callback1(int fsid, struct mfs_subobj_header *obj,
		    struct mfs_attr_header *attr, void *data);
char *vstream_schema_type(int type);
char *vstream_schema_attrib(int type, int attr);
void vstream_error( const char *format, ... );
int usage(char *name);
int main( int argc, char *argv[] );
void vstream_read_all(int fd, void *buf, int size);
void vstream_write_all(int fd, void *buf, int size);
int vstream_vstream_open_socket_out(char *host, int port);
void vstream_byte_swap(void *p, char *desc);
int vstream_startstream( char *fsid );
int64_t vstream_streamsize( );
void vstream_fsidtooffset( int chunk, int *fileNo, int64_t *fileChunk );
int vstream_load_chunk( char *fsid, unsigned char *buff, int size, int64_t foffset );
void vstream_list_streams( int longList );
int vstream_start();
